kubernetes:
  contexts:
    - name: hamk8s-cluster
      cluster:
        server: https://k8s.hamy.app:6443
        certificate-authority-data: ${K8S_CA_CERT}
      user:
        token: "${AGENT_TOKEN}"
  namespace: discord-gpt-bot
