---
stages:
- publish
- deploy
- test
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
publish:
  stage: publish
  image: docker:20.10
  services:
  - docker:20.10-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $TAG_COMMIT -t $TAG_LATEST .
  - docker push $TAG_COMMIT
  - docker push $TAG_LATEST
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
deploy:
  stage: deploy
  image: docker:20.10
  tags:
    - deployment
  services:
  - docker:20.10-dind
  before_script:
  - apk add --no-cache curl
  script:
  - chmod og= $ID_RSA
  - apk update && apk add openssh-client
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f haggle_bot || true"
  - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8940:3000 --name haggle_bot -e API_KEY=$API_KEY -e DISCORD_TOKEN=$DISCORD_TOKEN -e OPENAI_API_KEY=$OPENAI_API_KEY -e SENTRY_DSN=$SENTRY_DSN -e GCP_PROJECT_ID=$GCP_PROJECT_ID -e GCP_SERVICE_ACCOUNT_KEY=$GCP_SERVICE_ACCOUNT_KEY -v $CI_PROJECT_DIR/data-misc:/src/utils/data-misc $TAG_COMMIT"
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
postman_tests:
  stage: test
  script:
  - docker run -v $CI_PROJECT_DIR/tests:/etc/newman -t postman/newman:latest run "Discord_GPT_Bot_Testing.postman_collection.json" --reporters="cli"
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
