stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/krishamade/gpt_discord_bot:latest

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - apk add --no-cache curl
  script:
    - docker run -d -p 2222:8180 --name haggle_bot \
      -e DISCORD_TOKEN=$DISCORD_TOKEN \
      -e OPENAI_API_KEY=$OPENAI_API_KEY \
      -e SENTRY_DSN=$SENTRY_DSN \
      -v $CI_PROJECT_DIR/data-misc:/src/utils/data-misc $IMAGE_NAME
