stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/krishamade/gpt_discord_bot:latest

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - apk add --no-cache curl
    - echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
    - echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
    - echo "SENTRY_DSN=$SENTRY_DSN" >> .env
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker run -d -p 2222:8180 --name haggle_bot \
      -v $CI_PROJECT_DIR/data-misc:/src/utils/data-misc \
      $IMAGE_NAME
