stages:
  - package
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/<username>/<repo-name>:latest

package:
  stage: package
  script:
    - tar -czvf haggle_bot_files.tar.gz $CI_PROJECT_DIR/haggle_bot_files
  artifacts:
    paths:
      - haggle_bot_files.tar.gz

build:
  stage: build
  image: docker/compose:1.29.2
  script:
    - docker-compose build
    - docker tag haggle_bot $IMAGE_NAME
  artifacts:
    paths:
      - /var/run/docker.sock

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - apk add --no-cache curl
  script:
    - curl -o haggle_bot_files.tar.gz $CI_PIPELINE_ID/artifacts/haggle_bot_files.tar.gz
    - tar -xzvf haggle_bot_files.tar.gz
    - docker run -d -p 2222:8180 --name <container-name> -v $CI_PROJECT_DIR/haggle_bot_files:/src/utils $IMAGE_NAME